# Generated by Django 2.2.3 on 2019-07-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Vote',
        ),
    ]
